import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";

export default function PrivacyPolicyPage() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background relative selection:bg-primary/30">
      <div className="absolute top-8 left-8 z-50">
        <motion.button
          onClick={() => navigate("/")}
          whileHover={{ x: -4 }}
          className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors font-body font-medium"
        >
          <ArrowLeft className="w-5 h-5" />
          Back home
        </motion.button>
      </div>

      <div className="max-w-3xl mx-auto py-32 px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-8"
        >
          <h1 className="text-4xl md:text-5xl font-heading font-black text-foreground tracking-tight">
            Privacy Policy
          </h1>
          
          <div className="bg-primary/10 border-l-4 border-primary p-4 rounded-r-lg mb-8">
            <p className="text-primary font-body font-medium">As a secure clipboard and pastebin alternative, we treat data privacy as our core product feature, not just a legal requirement.</p>
          </div>

          <div className="prose prose-invert prose-lg max-w-none text-muted-foreground font-body leading-relaxed space-y-6">
            <p>
              This Privacy Policy explains how Clipalpha collects, uses, and protects information when you use our secure text and file sharing service.
            </p>
            
            <h2 className="text-2xl font-bold text-foreground mt-8">1. Information We Collect</h2>
            <p>
              To provide our secure clipboard service, our automated systems must collect diagnostic networking metadata. Our infrastructure only logs:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>General bandwidth, error logs, and platform analytics (to maintain system health).</li>
              <li>Encrypted ciphertext payloads generated by your Local Browser (meaning we cannot read the contents of your clips).</li>
            </ul>

            <h2 className="text-2xl font-bold text-foreground mt-8">2. Zero-Knowledge Constraints</h2>
            <p>
              All encryption processes execute strictly on the client side using robust AES-256 protocols. We have no mathematical capability to decrypt, access, or parse the files or text you transmit through our systems.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8">3. Infrastructure Log Retention</h2>
            <p>
              As a temporary pastebin alternative, all user-submitted encrypted payloads include an automated, mandatory expiration timestamp. Upon reaching this timestamp, our database forcefully purges the ciphertexts. Furthermore, no personally identifiable information (such as IP logs mapping to specific user identities) is permanently retained.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8">4. Legal Requests for Data</h2>
            <p>
              While we comply with lawful requests from authorities, due to our cryptographic zero-knowledge architecture, we are fundamentally unable to provide unencrypted user data, chat logs, pasted text, or readable files.
            </p>

            <p className="mt-12 text-sm text-muted-foreground">Last Updated: March 2026</p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
